### ISSUE TITLE
Dependencies to Ruby Gems: Installation Order

### ISSUE THREAD

**Issue by Rauldg** [rock-core/package_set#82]
Hi,

In my installation I am using ruby2.0 and some of the gems that are required depend (thin, sprockets and grape) on other gem (rack) which latest version does not support ruby2.0.

If I install the rack version 1.6.5 and then the other gems the installation goes well. 

I tried to fix with these changes in rock.osdeps-ruby20 in two ways:

1.
```
rack:
    gem:
        - rack<1.6.5
```

2.
```
thin:
    gem: 
        - rack<1.6.5
        - thin
sprockets:
    gem: 
        - rack<1.6.5
        - sprockets
grape:
    gem: 
        - rack<1.6.5
        - grape
```

But still autoproj tries to install rack latest gem instead of the version that is supported.

How should this be solved?
